### ISSUE TITLE
required libraries weren't mentioned

### ISSUE THREAD

**Issue by EMCP** [ComputerEnchiladas/mahrio-raspbian#2]
```
sudo apt-get install python-dev python-rpi.gpio wiringpi
```
then
```
sudo npm i -g bower
```

this fixed the `npm i` on this project

**Comment by EMCP** [comment]
subsequently, you need to add the media folder that `.env` is looking for

**Comment by EMCP** [comment]
now getting this 

```
pi@raspberrypi:~/Dev/ComputerEnchiladas/mahrio-raspbian $ sudo node server/index.js
Running Development!
(node:2448) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn irw ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
    at Module.runMain (module.js:609:11)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3
```

**Comment by JesusGuerrero** [comment]
Python? Don't recall this. Perhaps using Raspbian I did sudo apt-get update & sudo apt-get upgrade which updated the tools.

the irw error is new. I feel we will be experiencing "works on my machine" issues, which means we need to provide a way to replicate micro-sd volumes as a way to exchange exact configurations

**Comment by EMCP** [comment]
I had `node v7.x.x` installed, retrying `node server/index.js` again with `node 6.x.x`

Edit: No luck, still getting an error.

The logs seemed to be acting like I don't have permissions on a folder.  Yet I made my folder and also gave it `+rw` permissions with my user (`pi`)

**Comment by EMCP** [comment]
let me know what your media folder looks like as far as permissions 

```
mahrio-raspbian $ ls -la /media/pi/
total 12
drwxr-xr-x 3 pi   pi   4096 Oct 31 08:24 .
drwxr-xr-x 3 root root 4096 Oct 31 08:24 ..
drwxr-xr-x 2 pi   pi   4096 Oct 31 08:24 servo
```

here's my `.env`

```
NODE_ENV=development
NODE_URL=192.168.1.60
NODE_PORT=8080
MEDIA_DIRECTORY=/media/pi/servo/                             
```

way I'm executing this is 

mahrio-raspbian $ node server/index.js `

```
mahrio-raspbian $ node --version
v6.9.1
mahrio-raspbian $ npm --version
3.10.8
```

i ditched `nvm` too btw

**Comment by EMCP** [comment]
im trying the instructions I was looking for earlier.. found it again

https://github.com/ComputerEnchiladas/RaspberryPi/tree/master/01_Init

**Comment by EMCP** [comment]
if this works, I'd like to add this as a link in the `Readme.md`

**Comment by JesusGuerrero** [comment]
I think if you follow my raspbian setup with nodejs 6 it should work. let me know how it goes
