### ISSUE TITLE
where to put install wiringPi prereq?

### ISSUE THREAD

**Issue by EMCP** [ComputerEnchiladas/mahrio-raspbian#4]
Seems I cannot find where you ask me to install the following : 

`apt-get install wiringpi` , in order to get this project installed

Could you point out what section of the instructions I should update

https://github.com/ComputerEnchiladas/RaspberryPi/tree/master/01_Init

**Comment by JesusGuerrero** [comment]
at the end of Raspbian Software is good. After tight vnc

**Comment by EMCP** [comment]
https://github.com/ComputerEnchiladas/RaspberryPi/blob/master/01_Init/README.md
